# Homework 2

Please submit the solution to gradescope by 11:59 PM, Sept 26, Thursday.

**Name**: Conor Jones

**PID**: 730665579


# Problem 1  Sales Data Analysis (35 Points)
**Dataset:** You will work with a simulated dataset representing the monthly sales data for a fictional company over a period of 3 years (36 months). The dataset is provided as a NumPy array.

### 1.0 . Setup and Initialization

Import NumPy and initialize the dataset as a NumPy array.

In [36]:
import numpy as np

sales_data = np.array([207, 217, 244, 269, 247, 248, 273, 260, 243, 265, 263, 280,
                       310, 296, 313, 340, 336, 356, 335, 327, 374, 358, 376, 372,
                       405, 432, 425, 455, 443, 446, 439, 477, 454, 449, 494, 482])

### 1.1 Monthly Analysis (15 Points)
Using the `sales_data` array, perform the following tasks:
1. Calculate the total sales for each year, and store the result in a NumPy array `total_sales_per_year`. Display the `total_sales_per_year`. (2 points)

2. Calculate the average monthly sales for each year, and store the result in a NumPy array `average_monthly_sales_per_year`. Display the `average_monthly_sales_per_year`. (2 points)

3. Calculate the average season sales for each year, and store the result in a `3` by `4` NumPy array `average_season_sales_per_year`. Each row represent a year, and each column represent a season. Display the `average_season_sales_per_year`. (6 points)

4. Identify the month with the highest sales and the month with the lowest sales on average over the three year period. Store the numerical representation (1-12) of the month in the variables `max_sales_month` and `min_sales_month`. (5 points)

You can assume the years are in chronological order. For example, the first value represents sales in January of Year 1 and the last value represents sales in December of Year 3.


In [37]:
sales_data_reshaped = sales_data.reshape(3, 12)

total_sales_per_year = np.sum(sales_data_reshaped, axis=1)
print(total_sales_per_year)

[3016 4093 5401]


In [38]:
average_monthly_sales_per_year = np.mean(sales_data_reshaped, axis=1)
print(average_monthly_sales_per_year)

[251.33333333 341.08333333 450.08333333]


In [39]:
average_season_sales_per_year = np.mean(sales_data_reshaped.reshape(3, 4, 3), axis=2)
print(average_season_sales_per_year)


[[222.66666667 254.66666667 258.66666667 269.33333333]
 [306.33333333 344.         345.33333333 368.66666667]
 [420.66666667 448.         456.66666667 475.        ]]


In [40]:
average_sales_per_month = np.mean(sales_data_reshaped, axis=0)

max_sales_month = np.argmax(average_sales_per_month) + 1
min_sales_month = np.argmin(average_sales_per_month) + 1
print(max_sales_month, min_sales_month)

12 1


### 1.2 Growth Rate Calculation (5 Points)
Write a function `calculate_growth_rate(data)` that takes the `sales_data` array as input and returns the growth rates for each month in a NumPy array. You can assume the growth rate for the first month is 0.01.

Calculate the monthly growth rate of sales using the formula:

$$\text{growth\_rate}_i = \frac{\text{sales\_data}_i - \text{sales\_data}_{i-1}}{\text{sales\_data}_{i-1}}$$

Display the result of `calculate_growth_rate(sales_data)`.

In [66]:
def calculate_growth_rate(data):
    growth_rate = np.ones(len(data))
    growth_rate[0] = 0.01
    for i in range(1,len(data)):
        growth_rate[i] = (data[i] - data[i-1]) / data[i-1]
    return growth_rate

growth_rates = calculate_growth_rate(sales_data)
print(growth_rates)


[ 0.01        0.04830918  0.12442396  0.10245902 -0.08178439  0.00404858
  0.10080645 -0.04761905 -0.06538462  0.09053498 -0.00754717  0.06463878
  0.10714286 -0.04516129  0.05743243  0.08626198 -0.01176471  0.05952381
 -0.05898876 -0.0238806   0.14373089 -0.04278075  0.05027933 -0.0106383
  0.08870968  0.06666667 -0.0162037   0.07058824 -0.02637363  0.00677201
 -0.01569507  0.08656036 -0.04821803 -0.01101322  0.10022272 -0.0242915 ]


### 1.3 Growth Rate Summary (5 Points)
Identify the following months:

*   The months in the past three years saw the largest increase and the largest decrease in sales (i.e. from January to February of Year 1 we saw the largest decrease in sales)
*   The month on average with the largest increase and largest decrease in sales

Show both the python code and conclusion.


In [67]:
largest_growth = np.argmax(growth_rates) + 1
smallest_growth = np.argmin(growth_rates) + 1

reshaped_growth_rates = growth_rates.reshape(3, 12)
average_growth_rates_per_month = np.mean(reshaped_growth_rates, axis=0)

month_with_largest_average_growth = np.argmax(average_growth_rates_per_month) + 1

print(largest_growth, smallest_growth, month_with_largest_average_growth)


21 5 4


Largest increase in sales: January (Month 1), Largest decrease in sales: May (Month 5), Highest average growth over the 3 years: August (Month 8)

### 1.4 Moving Average (5 points)

Calculate the 3-month moving average of the `sales_data` and store the result in a NumPy array called `moving_average`. The calculation starts from the third month in Year 1.


The three-period moving average for month $t$ is calculated as:


$$\text{MA}_3(t) = \frac{x_t + x_{t-1} + x_{t-2}}{3}.$$

Where:
- $x_t$ is the sales in month $t$,
- $x_{t-1}$ is the sales in month $t-1$,
- $x_{t-2}$ is the sales in month $t-2$.

Display the `moving_average`.

In [44]:
moving_average = np.array([np.mean(sales_data[i:i+3]) for i in range(len(sales_data)-2)])
print(moving_average)


[222.66666667 243.33333333 253.33333333 254.66666667 256.
 260.33333333 258.66666667 256.         257.         269.33333333
 284.33333333 295.33333333 306.33333333 316.33333333 329.66666667
 344.         342.33333333 339.33333333 345.33333333 353.
 369.33333333 368.66666667 384.33333333 403.         420.66666667
 437.33333333 441.         448.         442.66666667 454.
 456.66666667 460.         465.66666667 475.        ]


### 1.5 Sales Anomaly Detection (5 points)

Write a function `sales_anomaly_detection(sales_data)` that takes the `sales_data` array as input, identify months where sales were significantly higher or lower than the previous month's sales (more than 12% change), and returns a dictionary mapping the month number (1-36) to the sales data for all anomalous months.

Display the result of `sales_anomaly_detection(sales_data)`.

In [69]:
def sales_anomaly_detection(sales_data):
    anomalies = {}
    growth_rates = calculate_growth_rate(sales_data)
    for i in range(1, len(growth_rates)):
        if abs(growth_rates[i]) > 0.12:
            anomalies[i+1] = sales_data[i]
    return anomalies

anomalous_months = sales_anomaly_detection(sales_data)
print(anomalous_months)


{3: 244, 21: 374}


# Problem 2: Analysis on the diamonds dataset (65 points)

Here is a brief description of the key columns in the **`diamonds`** dataset from Seaborn:


**`Carat`**: The weight of the diamond (continuous variable). Larger diamonds have higher carat values.


**`Cut`**: The quality of the diamond's cut (categorical variable).


**`Color`**: The diamond’s color grade (categorical variable). 


**`Clarity`**: The clarity of the diamond (categorical variable), which indicates how free the diamond is from internal flaws (inclusions) or external blemishes. It ranges from `IF` (Internally Flawless) to `I3` (Included).


**`Depth`**: The total depth percentage (continuous variable). It’s the ratio of the depth of the diamond to its average diameter.


**`Table`**: The width of the diamond’s top relative to its widest point (expressed as a percentage).


**`Price`**: The price of the diamond in US dollars (continuous variable).


**`x`**: Length of the diamond in millimeters (continuous variable).


**`y`**: Width of the diamond in millimeters (continuous variable).


**`z`**: Depth of the diamond in millimeters (continuous variable).

This dataset provides valuable features for exploring the relationship between various attributes and the price of diamonds.

#### 2.1 Load the dataset from a `diamonds.csv`. (1 point)

#### 2.2 How many different levels are there in the `cut` column? Provide the names of all levels. (4 points)

#### 2.3 Create three new columns, `x_in_inch`, `y_in_inch`, and `z_in_inch`, which convert the units of the original `x`, `y`, and `z` from millimeters to inches. Print the new table. (5 points)

#### 2.4 Create a new column called `Normalized_depth`, which scales the depth values between 0 and 1. (10 points)

The equation to normalize the `depth` column is given as:

$$
\text{depth}_{\text{normalized}} = \frac{\text{depth} - \min(\text{depth})}{\max(\text{depth}) - \min(\text{depth})}
$$

Where:
- $ \text{depth} $ is the original value,
- $ \min(\text{depth}) $ is the minimum value in the `depth` column,
- $ \max(\text{depth}) $ is the maximum value in the `depth` column.

Print the new table.

#### 2.5 Select the rows from the entire table where `clarity` is `SI2`. Drop the columns `color` and `clarity`. Print the selected table. (5 points)

#### 2.6 Suppose we have a linear model that predicts the price of a diamond using the `carat` value:

$$
\text{Predicted Price}  = 7769 \times \text{carat} - 2262.
$$

In the selected table from 2.5, create a new column called `Predicted_Price`, which contains the predicted price using the above formula. Display the new table. (10 points)

#### 2.7 In the new table from 2.6, calculate the difference between the actual price and the predicted price. How many rows have a prediction error that is smaller than 20% of the actual price? (5 points)

#### 2.8 Sort the table in 2.7 by 'carat' column in increasing order. Display the first 3 rows and last 3 rows of the sorted table. (5 points). Concatenate the first 3 rows and last 3 rows into a new table. (5 points) (10 points in total)

#### 2.9 In the table from 2.7, what is the value of `carat` that has the smallest prediction error? What is the value of `carat` that has the largest prediction error. (5 points)

#### 2.10 In the orignal entire table, calculate the average prices for each level of cut. Display the result as a pd.Series. Does a better cut lead to a higher price? (10 points)

In [46]:
import pandas as pd

# Load the dataset
diamonds = pd.read_csv('diamonds.csv')
print(diamonds.head())


   Carat      Cut Color Clarity  depth  table  Price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75


In [47]:
cut_levels = diamonds['Cut'].unique()
print(cut_levels)
print(len(cut_levels))


['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
5


In [61]:
diamonds['x_in_inch'] = diamonds['x'] * 0.03937
diamonds['y_in_inch'] = diamonds['y'] * 0.03937
diamonds['z_in_inch'] = diamonds['z'] * 0.03937
print(diamonds[['x_in_inch', 'y_in_inch', 'z_in_inch']])


       x_in_inch  y_in_inch  z_in_inch
0       0.155512   0.156693   0.095669
1       0.153149   0.151181   0.090945
2       0.159448   0.160236   0.090945
3       0.165354   0.166535   0.103543
4       0.170866   0.171260   0.108268
...          ...        ...        ...
53935   0.226378   0.226771   0.137795
53936   0.224015   0.226378   0.142126
53937   0.222834   0.223622   0.140157
53938   0.242126   0.240944   0.147244
53939   0.229527   0.231102   0.143307

[53940 rows x 3 columns]


In [49]:
diamonds['Normalized_depth'] = (diamonds['depth'] - diamonds['depth'].min()) / (diamonds['depth'].max() - diamonds['depth'].min())
print(diamonds[['depth', 'Normalized_depth']])


       depth  Normalized_depth
0       61.5          0.513889
1       59.8          0.466667
2       56.9          0.386111
3       62.4          0.538889
4       63.3          0.563889
...      ...               ...
53935   60.8          0.494444
53936   63.1          0.558333
53937   62.8          0.550000
53938   61.0          0.500000
53939   62.2          0.533333

[53940 rows x 2 columns]


In [50]:
diamonds['Normalized_depth'] = (diamonds['depth'] - diamonds['depth'].min()) / (diamonds['depth'].max() - diamonds['depth'].min())
print(diamonds[['depth', 'Normalized_depth']])


       depth  Normalized_depth
0       61.5          0.513889
1       59.8          0.466667
2       56.9          0.386111
3       62.4          0.538889
4       63.3          0.563889
...      ...               ...
53935   60.8          0.494444
53936   63.1          0.558333
53937   62.8          0.550000
53938   61.0          0.500000
53939   62.2          0.533333

[53940 rows x 2 columns]


In [51]:
diamonds_SI2 = diamonds[diamonds['Clarity'] == 'SI2'].drop(columns=['Color', 'Clarity'])
print(diamonds_SI2)


       Carat        Cut  depth  table  Price     x     y     z  x_in_inch  \
0       0.23      Ideal   61.5   55.0    326  3.95  3.98  2.43   0.155512   
4       0.31       Good   63.3   58.0    335  4.34  4.35  2.75   0.170866   
13      0.31      Ideal   62.2   54.0    344  4.35  4.37  2.71   0.171260   
14      0.20    Premium   60.2   62.0    345  3.79  3.75  2.27   0.149212   
16      0.30      Ideal   62.0   54.0    348  4.31  4.34  2.68   0.169685   
...      ...        ...    ...    ...    ...   ...   ...   ...        ...   
53902   0.77  Very Good   59.9   61.0   2753  5.98  6.01  3.59   0.235433   
53915   0.77      Ideal   62.1   56.0   2753  5.84  5.86  3.63   0.229921   
53928   0.79    Premium   61.4   58.0   2756  6.03  5.96  3.68   0.237401   
53938   0.86    Premium   61.0   58.0   2757  6.15  6.12  3.74   0.242126   
53939   0.75      Ideal   62.2   55.0   2757  5.83  5.87  3.64   0.229527   

       y_in_inch  z_in_inch  Normalized_depth  
0       0.156693   0.095669

In [52]:
diamonds_SI2['Predicted_Price'] = 7769 * diamonds_SI2['Carat'] - 2262
print(diamonds_SI2[['Carat', 'Predicted_Price']])


       Carat  Predicted_Price
0       0.23          -475.13
4       0.31           146.39
13      0.31           146.39
14      0.20          -708.20
16      0.30            68.70
...      ...              ...
53902   0.77          3720.13
53915   0.77          3720.13
53928   0.79          3875.51
53938   0.86          4419.34
53939   0.75          3564.75

[9194 rows x 2 columns]


In [53]:
diamonds_SI2['Prediction_Error'] = abs(diamonds_SI2['Price'] - diamonds_SI2['Predicted_Price']) / diamonds_SI2['Price']

small_error_count = len(diamonds_SI2[diamonds_SI2['Prediction_Error'] < 0.2])
print(small_error_count)


2169


In [54]:
sorted_diamonds = diamonds_SI2.sort_values(by='Carat')
first_three = sorted_diamonds.head(3)
last_three = sorted_diamonds.tail(3)

concatenated = pd.concat([first_three, last_three])
print(concatenated)


       Carat        Cut  depth  table  Price     x     y     z  x_in_inch  \
14      0.20    Premium   60.2   62.0    345  3.79  3.75  2.27   0.149212   
43989   0.21    Premium   61.9   56.0    394  3.84  3.82  2.37   0.151181   
0       0.23      Ideal   61.5   55.0    326  3.95  3.98  2.43   0.155512   
27518   3.01       Good   63.9   60.0  18242  9.06  9.01  5.77   0.356692   
26100   3.04  Very Good   63.2   59.0  15354  9.14  9.07  5.75   0.359842   
27638   3.04    Premium   59.3   60.0  18559  9.51  9.46  5.62   0.374409   

       y_in_inch  z_in_inch  Normalized_depth  Predicted_Price  \
14      0.147638   0.089370          0.477778          -708.20   
43989   0.150393   0.093307          0.525000          -630.51   
0       0.156693   0.095669          0.513889          -475.13   
27518   0.354724   0.227165          0.580556         21122.69   
26100   0.357086   0.226378          0.561111         21355.76   
27638   0.372440   0.221259          0.452778         21355.76  

In [55]:
min_error_carat = diamonds_SI2.loc[diamonds_SI2['Prediction_Error'].idxmin()]['Carat']
max_error_carat = diamonds_SI2.loc[diamonds_SI2['Prediction_Error'].idxmax()]['Carat']
print(min_error_carat, max_error_carat)


1.79 0.2


In [56]:
average_price_by_cut = diamonds.groupby('Cut')['Price'].mean()
print(average_price_by_cut)


Cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: Price, dtype: float64
